git:
  submodules: true
language: scala
# run on new infrastructure
sudo: false

cache:
  directories:
    $HOME/.ivy2
    $INSTALL_DIR

env:
  global:
    INSTALL_DIR=$TRAVIS_BUILD_DIR/install
    VERILATOR_ROOT=$INSTALL_DIR
    PATH=$PATH:$VERILATOR_ROOT/bin:$TRAVIS_BUILD_DIR/utils/bin

install:
  # Install dependencies
  - bash .install_verilator.sh
  - bash .install_deps.sh

script:
  - java -XX:+CMSClassUnloadingEnabled -XX:MaxPermSize=256m -Xmx8G -Xss128M -jar $INSTALL_DIR/rocket-chip/sbt-launch.jar -Dsbt.ivy.home="$HOME/.ivy2" "testOnly dspblocks.DspBlockTesterSpec"
  # - sbt "testOnly dspblocks.DspBlockTesterSpec"
  # AsyncResetReg.v is missing on travis
  # - sbt "testOnly jtag.JtagAxiSpec"

